In [1]:
import numpy as np
import pandas as pd
# import pandas as pd
df=pd.read_csv('original_train_titanic.csv')

In [2]:
df

Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0        1      0           228414  26.0000   NaN        S         1  
1        0      0         A/5 2466   8.0500   NaN        S         0  
2        0      0           250655  26.0000   NaN        S         0  
3        0      4           349909  21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...    ...              ...      ...   ...      ...       ...  
663      0      0       SO/C 14885  10.5000   NaN        S         1  
664      0      0           372622   7.7500   NaN        Q         0  
665      0      0             1601  56.4958   NaN        S         1  
666      0      0             7553   9.8375   NaN        S         0  
667      1      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [3]:
del df["Ticket"]

In [4]:
df.describe()

Pclass         Age       SibSp       Parch        Fare    Survived
count  668.000000  536.000000  668.000000  668.000000  668.000000  668.000000
mean     2.296407   29.700560    0.528443    0.407186   32.064552    0.402695
std      0.831638   14.240257    1.080327    0.854695   45.320835    0.490808
min      1.000000    0.670000    0.000000    0.000000    0.000000    0.000000
25%      2.000000   21.000000    0.000000    0.000000    7.925000    0.000000
50%      3.000000   29.000000    0.000000    0.000000   14.750000    0.000000
75%      3.000000   38.250000    1.000000    0.000000   31.275000    1.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200    1.000000

In [5]:
del df["Name"]

In [6]:
def h(n):
    a = np.round(n)
    return(int(a))
    pass
df["Fare"] = df.Fare.apply(h)

In [7]:
df

Pclass     Sex   Age  SibSp  Parch  Fare Cabin Embarked  Survived
0         2  female  29.0      1      0    26   NaN        S         1
1         3    male   NaN      0      0     8   NaN        S         0
2         2    male  39.0      0      0    26   NaN        S         0
3         3  female  29.0      0      4    21   NaN        S         0
4         3    male  25.0      0      0     7   NaN        S         0
..      ...     ...   ...    ...    ...   ...   ...      ...       ...
663       2  female  17.0      0      0    10   NaN        S         1
664       3    male   NaN      0      0     8   NaN        Q         0
665       3    male  32.0      0      0    56   NaN        S         1
666       3  female  22.0      0      0    10   NaN        S         0
667       3  female   NaN      1      0    16   NaN        Q         1

[668 rows x 9 columns]

In [8]:
def h(s):
    if s == "S":
        return 1
    elif s == "Q":
        return 2
    else:
        return 3
    pass
df["Embarked"] = df.Embarked.apply(h)

In [9]:
df.describe()

Pclass         Age       SibSp       Parch        Fare    Embarked  \
count  668.000000  536.000000  668.000000  668.000000  668.000000  668.000000   
mean     2.296407   29.700560    0.528443    0.407186   32.065868    1.476048   
std      0.831638   14.240257    1.080327    0.854695   45.327843    0.807217   
min      1.000000    0.670000    0.000000    0.000000    0.000000    1.000000   
25%      2.000000   21.000000    0.000000    0.000000    8.000000    1.000000   
50%      3.000000   29.000000    0.000000    0.000000   14.500000    1.000000   
75%      3.000000   38.250000    1.000000    0.000000   31.000000    2.000000   
max      3.000000   80.000000    8.000000    6.000000  512.000000    3.000000   

         Survived  
count  668.000000  
mean     0.402695  
std      0.490808  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      1.000000

In [10]:
def g(s):
    if s == "male":
        return 0
    else:
        return 1
    pass
df["Sex"] = df.Sex.apply(g)

In [11]:
a = df[df.Pclass == 1]
sur_1_age = a.Age.mean()
sur_1_age = np.round(sur_1_age)
print(sur_1_age)

b = df[df.Pclass == 2]
sur_2_age = b.Age.mean()
sur_2_age = np.round(sur_2_age)
print(sur_2_age)

c = df[df.Pclass == 3]
sur_3_age = c.Age.mean()
sur_3_age = np.round(sur_3_age)
print(sur_3_age)

37.0
30.0
26.0


In [12]:
def f(n):
    Age = n[0]
    P = n[1]
    if pd.isnull(Age):
        if P == 1:
            return int(sur_1_age)
        elif P == 2:
            return int(sur_2_age)
        else:
            return int(sur_3_age)
    else:
        return int(Age)
        
df["Age"] = df[["Age", "Pclass"]].apply(f,axis = 1)

In [13]:
df["Age"]

0      29
1      26
2      39
3      29
4      25
       ..
663    17
664    26
665    32
666    22
667    26
Name: Age, Length: 668, dtype: int64

In [14]:
df.describe()

Pclass         Sex         Age       SibSp       Parch        Fare  \
count  668.000000  668.000000  668.000000  668.000000  668.000000  668.000000   
mean     2.296407    0.360778   29.393713    0.528443    0.407186   32.065868   
std      0.831638    0.480586   12.911616    1.080327    0.854695   45.327843   
min      1.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      2.000000    0.000000   23.000000    0.000000    0.000000    8.000000   
50%      3.000000    0.000000   27.000000    0.000000    0.000000   14.500000   
75%      3.000000    1.000000   37.000000    1.000000    0.000000   31.000000   
max      3.000000    1.000000   80.000000    8.000000    6.000000  512.000000   

         Embarked    Survived  
count  668.000000  668.000000  
mean     1.476048    0.402695  
std      0.807217    0.490808  
min      1.000000    0.000000  
25%      1.000000    0.000000  
50%      1.000000    0.000000  
75%      2.000000    1.000000  
max      3.000000    1.000000

In [16]:
del df["Cabin"]

In [18]:
data = df.to_numpy()

In [19]:
x = data[:,:-1]
# import sklearn.preprocessing as pp
# x = pp.scale(x)
y = data[:,-1]
print(x.shape)
print(y.shape)

(668, 7)
(668,)


In [20]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C=2,multi_class='auto')
clf.fit(x,y)

/Users/rajkumarmittal/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=2, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
clf.score(x,y)

0.7934131736526946

In [22]:
clf.predict_proba(x)[1]

array([0.88057033, 0.11942967])

In [23]:
clf.predict(x) - y

array([ 0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0, -1,
        0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0,
        0,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  1,  0,  0,
       -1,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  1,  0,  0, -1,  0,  0,  0,  0,  0,  0, -1, -1,
        1, -1,  1,  0,  0,  0,  0,  0,  0,  0, -1,  0,  1,  0,  0,  0,  0,
        0,  0,  0,  0,  1,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0, -1, -1,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,
        0,  0,  0,  0,  0,  0,  1, -1,  1,  0, -1,  0,  0,  1,  0,  0,  0,
        0, -1,  0,  0,  0,  0, -1, -1,  0,  0,  0,  1,  0,  1, -1,  0,  0,
        0,  0,  0, -1, -1,  0,  0,  1,  0, -1, -1,  0,  0,  0, -1,  0,  0,
        0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,
        0,  1,  0,  0,  0

In [24]:
d=pd.read_csv('original_test_titanic.csv')
d.describe()


Pclass         Age       SibSp       Parch        Fare
count  223.000000  178.000000  223.000000  223.000000  223.000000
mean     2.345291   29.694775    0.506726    0.304933   32.622551
std      0.850047   15.398053    1.169700    0.634108   61.062047
min      1.000000    0.420000    0.000000    0.000000    0.000000
25%      2.000000   19.250000    0.000000    0.000000    7.879200
50%      3.000000   27.000000    0.000000    0.000000   12.475000
75%      3.000000   37.750000    1.000000    0.000000   30.035400
max      3.000000   71.000000    8.000000    2.000000  512.329200

In [25]:
del d["Ticket"]
del d["Name"]
def h(n):
    a = np.round(n)
    return(int(a))
    pass
d["Fare"] = d.Fare.apply(h)
def h(s):
    if s == "S":
        return 1
    elif s == "Q":
        return 2
    else:
        return 3
    pass
d["Embarked"] = d.Embarked.apply(h)

In [26]:
def g(s):
    if s == "male":
        return 0
    else:
        return 1
    pass
d["Sex"] = d.Sex.apply(g)

In [27]:
a = d[d.Pclass == 1]
sur_1_age = a.Age.mean()
sur_1_age = np.round(sur_1_age)
print(sur_1_age)

b = d[d.Pclass == 2]
sur_2_age = b.Age.mean()
sur_2_age = np.round(sur_2_age)
print(sur_2_age)

c = d[d.Pclass == 3]
sur_3_age = c.Age.mean()
sur_3_age = np.round(sur_3_age)
print(sur_3_age)
# a = d[d.Pclass == 1]
# a_m = a[a.Sex == 0]
# sur_m_age = a_m.Age.mean()
# sur_m_age = np.round(sur_m_age)
# print(sur_m_age)
# a_f = a[a.Sex == 1]
# sur_f_age = a_f.Age.mean()
# sur_f_age = np.round(sur_f_age)
# print(sur_f_age)


# b = d[d.Pclass == 2]
# b_m = b[b.Sex == 0]
# sur_m1_age = b_m.Age.mean()
# sur_m1_age = np.round(sur_m1_age)
# print(sur_m1_age)
# b_f = b[b.Sex == 1]
# sur_f1_age = b_f.Age.mean()
# sur_f1_age = np.round(sur_f1_age)
# print(sur_f1_age)


# c = d[d.Pclass == 3]
# c_m = c[c.Sex == 0]
# sur_m2_age = c_m.Age.mean()
# sur_m2_age = np.round(sur_m2_age)
# print(sur_m2_age)
# c_f = c[c.Sex == 1]
# sur_f2_age = c_f.Age.mean()
# sur_f2_age = np.round(sur_f2_age)
# print(sur_f2_age)

41.0
31.0
23.0


In [28]:
def f(n):
    Age = n[0]
    P = n[1]
    if pd.isnull(Age):
        if P == 1:
            return int(sur_1_age)
        elif P == 2:
            return int(sur_2_age)
        else:
            return int(sur_3_age)
    else:
        return int(Age)
        
d["Age"] = d[["Age", "Pclass"]].apply(f,axis = 1)
# def f(n):
#     Age = n[0]
#     P = n[1]
#     S = n[2]
#     if pd.isnull(Age):
#         if P == 1:
#             if S == 1:
#                 return int(sur_m_age)
#             else:
#                 return int(sur_f_age)
        
#         elif P == 2:
#             if S == 1:
#                 return int(sur_m1_age)
#             else:
#                 return int(sur_f1_age)
#         else:
#             if S == 1:
#                 return int(sur_m2_age)
#             else:
#                 return int(sur_f2_age)
#     else:
#         return int(Age)
        
# d["Age"] = d[["Age", "Pclass", "Sex"]].apply(f,axis = 1)

In [29]:
del d["Cabin"]

In [30]:
d

Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
0         2    0    8      1      1    37         1
1         1    1   49      0      0    26         1
2         3    0   23      0      0     8         2
3         2    1   24      2      1    27         1
4         1    0   36      0      0    26         1
..      ...  ...  ...    ...    ...   ...       ...
218       3    0   20      1      0     8         1
219       1    0   45      0      0    27         1
220       1    1   17      1      0   109         3
221       3    0   43      0      0     6         1
222       2    0   36      0      2    26         1

[223 rows x 7 columns]

In [31]:
data = d.to_numpy()

In [32]:
data

array([[  2,   0,   8, ...,   1,  37,   1],
       [  1,   1,  49, ...,   0,  26,   1],
       [  3,   0,  23, ...,   0,   8,   2],
       ...,
       [  1,   1,  17, ...,   0, 109,   3],
       [  3,   0,  43, ...,   0,   6,   1],
       [  2,   0,  36, ...,   2,  26,   1]])

In [33]:
y_pred = clf.predict(data)

In [34]:
y_pred

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0])

In [35]:
y_pred.shape

(223,)

In [36]:
np.savetxt("0000000000002429_test_titanic_x_test.csv",y_pred, delimiter =',', fmt='%1.0f')